.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 Arun Kumar Pariyar <openarungeek@gmail.com>,
.\"
.TH "MAHONICONV" "1" "2020-09-27" "mahoniconv"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)

.SH NAME
mahoniconv \- Character-set conversion library implemented in Go. (program)

.SH SYNOPSIS
.B mahoniconv
.RI -f
.RI <source-charset>
.RI -o
.RI <destination-charset>

.SH DESCRIPTION
This manual page documents briefly the
.B mahoniconv
command as provided by
.B mahonia
package.
.PP


.SH AUTHOR
.PP
.B mahoniconv
is written by axgle.
.PP
This manual page was written by
.MT openarungeek@\:gmail.com
Arun Kumar Pariyar
.ME
for the Debian Project (but may be used by others).
